apiVersion: extensions/v1beta1
kind: nginx
metadata:
  name: rancher-ingress
  annotations:
spec:
  rules:
  - host: {{ .Values.fqdn }}  # FQDN to access rancher server
    http:
      paths:
      - backend:
          serviceName: rancher-service
