kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rancher
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: rancher
    spec:
      serviceAccountName: rancher-admin
      containers:
      - image: rancher/rancher:{{ .Values.rancher_image_tag }}
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
