apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  type: NodePort
  ports:
  - name: httpd
    port: {{ .Values.service.port }}
    targetPort: httpd
  selector:
    app: httpd
