apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: httpd
    port: {{ .Values.service.port }}
    targetPort: httpd
    {{- if .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: httpd
