apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: httpd
    port: 
    targetPort: httpd
  selector:
    app: httpd
