apiVersion: v1
name: IProject
description: Kant en klare webserver voor het I-Project.
version: 1.0.0
home: https://www.dream-it.cloud
icon: https://github.com/rancher/ui/blob/master/public/assets/images/logos/welcome-cow.svg
keywords:
  - iproject
maintainers:
  - name: Dream-IT


